/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/kit/program-client-core";
import { findStatePda } from "../pdas";
import { SEEKER_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const BUMP_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  102, 163, 91, 221, 146, 88, 184, 142,
]);

export function getBumpDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(BUMP_DISCRIMINATOR);
}

export type BumpInstruction<
  TProgram extends string = typeof SEEKER_PROGRAM_PROGRAM_ADDRESS,
  TAccountState extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountState extends string
        ? WritableAccount<TAccountState>
        : TAccountState,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type BumpInstructionData = { discriminator: ReadonlyUint8Array };

export type BumpInstructionDataArgs = {};

export function getBumpInstructionDataEncoder(): FixedSizeEncoder<BumpInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: BUMP_DISCRIMINATOR }),
  );
}

export function getBumpInstructionDataDecoder(): FixedSizeDecoder<BumpInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getBumpInstructionDataCodec(): FixedSizeCodec<
  BumpInstructionDataArgs,
  BumpInstructionData
> {
  return combineCodec(
    getBumpInstructionDataEncoder(),
    getBumpInstructionDataDecoder(),
  );
}

export type BumpAsyncInput<
  TAccountState extends string = string,
  TAccountAuthority extends string = string,
> = {
  state?: Address<TAccountState>;
  authority: TransactionSigner<TAccountAuthority>;
};

export async function getBumpInstructionAsync<
  TAccountState extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof SEEKER_PROGRAM_PROGRAM_ADDRESS,
>(
  input: BumpAsyncInput<TAccountState, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress },
): Promise<BumpInstruction<TProgramAddress, TAccountState, TAccountAuthority>> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SEEKER_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    state: { value: input.state ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.state.value) {
    accounts.state.value = await findStatePda({
      authority: getAddressFromResolvedInstructionAccount(
        "authority",
        accounts.authority.value,
      ),
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("state", accounts.state),
      getAccountMeta("authority", accounts.authority),
    ],
    data: getBumpInstructionDataEncoder().encode({}),
    programAddress,
  } as BumpInstruction<TProgramAddress, TAccountState, TAccountAuthority>);
}

export type BumpInput<
  TAccountState extends string = string,
  TAccountAuthority extends string = string,
> = {
  state: Address<TAccountState>;
  authority: TransactionSigner<TAccountAuthority>;
};

export function getBumpInstruction<
  TAccountState extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof SEEKER_PROGRAM_PROGRAM_ADDRESS,
>(
  input: BumpInput<TAccountState, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress },
): BumpInstruction<TProgramAddress, TAccountState, TAccountAuthority> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SEEKER_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    state: { value: input.state ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("state", accounts.state),
      getAccountMeta("authority", accounts.authority),
    ],
    data: getBumpInstructionDataEncoder().encode({}),
    programAddress,
  } as BumpInstruction<TProgramAddress, TAccountState, TAccountAuthority>);
}

export type ParsedBumpInstruction<
  TProgram extends string = typeof SEEKER_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    state: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: BumpInstructionData;
};

export function parseBumpInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedBumpInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { state: getNextAccount(), authority: getNextAccount() },
    data: getBumpInstructionDataDecoder().decode(instruction.data),
  };
}
