/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { SEEKER_PROGRAM_PROGRAM_ADDRESS } from "../programs";

/** Overflow: Increment overflowed. */
export const SEEKER_PROGRAM_ERROR__OVERFLOW = 0x1770; // 6000
/** Unauthorized: Only the authority may perform this action. */
export const SEEKER_PROGRAM_ERROR__UNAUTHORIZED = 0x1771; // 6001

export type SeekerProgramError =
  | typeof SEEKER_PROGRAM_ERROR__OVERFLOW
  | typeof SEEKER_PROGRAM_ERROR__UNAUTHORIZED;

let seekerProgramErrorMessages: Record<SeekerProgramError, string> | undefined;
if (process.env["NODE_ENV"] !== "production") {
  seekerProgramErrorMessages = {
    [SEEKER_PROGRAM_ERROR__OVERFLOW]: `Increment overflowed.`,
    [SEEKER_PROGRAM_ERROR__UNAUTHORIZED]: `Only the authority may perform this action.`,
  };
}

export function getSeekerProgramErrorMessage(code: SeekerProgramError): string {
  if (process.env["NODE_ENV"] !== "production") {
    return (seekerProgramErrorMessages as Record<SeekerProgramError, string>)[
      code
    ];
  }

  return "Error message not available in production bundles.";
}

export function isSeekerProgramError<
  TProgramErrorCode extends SeekerProgramError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    SEEKER_PROGRAM_PROGRAM_ADDRESS,
    code,
  );
}
