/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const TALLY_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  126, 11, 29, 33, 32, 101, 239, 25,
]);

export function getTallyDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(TALLY_DISCRIMINATOR);
}

export type Tally = {
  discriminator: ReadonlyUint8Array;
  authority: Address;
  tally: bigint;
  bump: number;
};

export type TallyArgs = {
  authority: Address;
  tally: number | bigint;
  bump: number;
};

/** Gets the encoder for {@link TallyArgs} account data. */
export function getTallyEncoder(): FixedSizeEncoder<TallyArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["authority", getAddressEncoder()],
      ["tally", getU64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: TALLY_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Tally} account data. */
export function getTallyDecoder(): FixedSizeDecoder<Tally> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["authority", getAddressDecoder()],
    ["tally", getU64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link Tally} account data. */
export function getTallyCodec(): FixedSizeCodec<TallyArgs, Tally> {
  return combineCodec(getTallyEncoder(), getTallyDecoder());
}

export function decodeTally<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Tally, TAddress>;
export function decodeTally<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Tally, TAddress>;
export function decodeTally<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Tally, TAddress> | MaybeAccount<Tally, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getTallyDecoder(),
  );
}

export async function fetchTally<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Tally, TAddress>> {
  const maybeAccount = await fetchMaybeTally(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeTally<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Tally, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeTally(maybeAccount);
}

export async function fetchAllTally(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Tally>[]> {
  const maybeAccounts = await fetchAllMaybeTally(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeTally(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Tally>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeTally(maybeAccount));
}

export function getTallySize(): number {
  return 49;
}
