/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getAddressEncoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export type StateSeeds = {
  authority: Address;
};

export async function findStatePda(
  seeds: StateSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "4dQJbKb7PdNYLJVjdqEhh1TceLEzhy62BG2iZf93SVX6" as Address<"4dQJbKb7PdNYLJVjdqEhh1TceLEzhy62BG2iZf93SVX6">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(new Uint8Array([116, 97, 108, 108, 121])),
      getAddressEncoder().encode(seeds.authority),
    ],
  });
}
