/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  extendClient,
  fixEncoderSize,
  getBytesEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
  SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
  SolanaError,
  type Address,
  type ClientWithRpc,
  type ClientWithTransactionPlanning,
  type ClientWithTransactionSending,
  type ExtendedClient,
  type GetAccountInfoApi,
  type GetMultipleAccountsApi,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfFetchFunctions,
  addSelfPlanAndSendFunctions,
  type SelfFetchFunctions,
  type SelfPlanAndSendFunctions,
} from "@solana/kit/program-client-core";
import { getTallyCodec, type Tally, type TallyArgs } from "../accounts";
import {
  getBumpInstructionAsync,
  getInitializeInstructionAsync,
  parseBumpInstruction,
  parseInitializeInstruction,
  type BumpAsyncInput,
  type InitializeAsyncInput,
  type ParsedBumpInstruction,
  type ParsedInitializeInstruction,
} from "../instructions";
import { findStatePda } from "../pdas";

export const SEEKER_PROGRAM_PROGRAM_ADDRESS =
  "4dQJbKb7PdNYLJVjdqEhh1TceLEzhy62BG2iZf93SVX6" as Address<"4dQJbKb7PdNYLJVjdqEhh1TceLEzhy62BG2iZf93SVX6">;

export enum SeekerProgramAccount {
  Tally,
}

export function identifySeekerProgramAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SeekerProgramAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([126, 11, 29, 33, 32, 101, 239, 25]),
      ),
      0,
    )
  ) {
    return SeekerProgramAccount.Tally;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
    { accountData: data, programName: "seekerProgram" },
  );
}

export enum SeekerProgramInstruction {
  Bump,
  Initialize,
}

export function identifySeekerProgramInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SeekerProgramInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([102, 163, 91, 221, 146, 88, 184, 142]),
      ),
      0,
    )
  ) {
    return SeekerProgramInstruction.Bump;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237]),
      ),
      0,
    )
  ) {
    return SeekerProgramInstruction.Initialize;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    { instructionData: data, programName: "seekerProgram" },
  );
}

export type ParsedSeekerProgramInstruction<
  TProgram extends string = "4dQJbKb7PdNYLJVjdqEhh1TceLEzhy62BG2iZf93SVX6",
> =
  | ({
      instructionType: SeekerProgramInstruction.Bump;
    } & ParsedBumpInstruction<TProgram>)
  | ({
      instructionType: SeekerProgramInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>);

export function parseSeekerProgramInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedSeekerProgramInstruction<TProgram> {
  const instructionType = identifySeekerProgramInstruction(instruction);
  switch (instructionType) {
    case SeekerProgramInstruction.Bump: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SeekerProgramInstruction.Bump,
        ...parseBumpInstruction(instruction),
      };
    }
    case SeekerProgramInstruction.Initialize: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SeekerProgramInstruction.Initialize,
        ...parseInitializeInstruction(instruction),
      };
    }
    default:
      throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
        {
          instructionType: instructionType as string,
          programName: "seekerProgram",
        },
      );
  }
}

export type SeekerProgramPlugin = {
  accounts: SeekerProgramPluginAccounts;
  instructions: SeekerProgramPluginInstructions;
  pdas: SeekerProgramPluginPdas;
  identifyAccount: typeof identifySeekerProgramAccount;
  identifyInstruction: typeof identifySeekerProgramInstruction;
  parseInstruction: typeof parseSeekerProgramInstruction;
};

export type SeekerProgramPluginAccounts = {
  tally: ReturnType<typeof getTallyCodec> &
    SelfFetchFunctions<TallyArgs, Tally>;
};

export type SeekerProgramPluginInstructions = {
  bump: (
    input: BumpAsyncInput,
  ) => ReturnType<typeof getBumpInstructionAsync> & SelfPlanAndSendFunctions;
  initialize: (
    input: InitializeAsyncInput,
  ) => ReturnType<typeof getInitializeInstructionAsync> &
    SelfPlanAndSendFunctions;
};

export type SeekerProgramPluginPdas = { state: typeof findStatePda };

export type SeekerProgramPluginRequirements = ClientWithRpc<
  GetAccountInfoApi & GetMultipleAccountsApi
> &
  ClientWithTransactionPlanning &
  ClientWithTransactionSending;

export function seekerProgramProgram() {
  return <T extends SeekerProgramPluginRequirements>(
    client: T,
  ): ExtendedClient<T, { seekerProgram: SeekerProgramPlugin }> => {
    return extendClient(client, {
      seekerProgram: <SeekerProgramPlugin>{
        accounts: { tally: addSelfFetchFunctions(client, getTallyCodec()) },
        instructions: {
          bump: (input) =>
            addSelfPlanAndSendFunctions(client, getBumpInstructionAsync(input)),
          initialize: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializeInstructionAsync(input),
            ),
        },
        pdas: { state: findStatePda },
        identifyAccount: identifySeekerProgramAccount,
        identifyInstruction: identifySeekerProgramInstruction,
        parseInstruction: parseSeekerProgramInstruction,
      },
    });
  };
}
